### ISSUE TITLE
Default LV2 Path for Windows

### ISSUE THREAD

**Issue by x42** [lv2/lilv#42]
https://github.com/lv2/lilv/blob/b8a07a18da02b9613ab94f35c6d5629bb7223a2c/src/lilv_config.h#L122

This should use backslashes for dir separators: 
```C++
#    define LILV_DEFAULT_LV2_PATH "%APPDATA%\\LV2;%COMMONPROGRAMFILES%\\LV2"
```

Likewise the following line adds an extra '%' which breaks discovery
https://github.com/lv2/lilv/blob/b8a07a18da02b9613ab94f35c6d5629bb7223a2c/wscript#L269
this leads to `"-DLILV_DEFAULT_LV2_PATH=\"%%APPDATA%%\\\\LV2;%%COMMONPROGRAMFILES%%\\\\LV2\""`

The correct default path at runtime (after expanding escaped backslashes) that is used in `lilv_world_load_all()` should be
`%APPDATA%\LV2;%COMMONPROGRAMFILES%\LV2`

**Comment by drobilla** [comment]
Sigh, MinGW.  The percent thing is tricky because it's a Windows shell issue.  I will just assume that if the build is happening on Windows with MSVC then the Windows command line is being used, which will break things for bash on Windows, but... oh well.

Fixed in 32b00be75b5d1cf33d5c8b25b7c6448249943ce6 and 13d7c055c456d4b187e97b5909614939b87ff5c5, thanks.
